"""Create Table supermarkets

Revision ID: 619fe6608d54
Revises: 
Create Date: 2022-02-19 00:37:40.063879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619fe6608d54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supermarkets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supermarkets')
    # ### end Alembic commands ###
