"""Create product model and made a relationship with supermarket model

Revision ID: 92d4009950d3
Revises: 619fe6608d54
Create Date: 2022-02-19 01:11:38.488265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d4009950d3'
down_revision = '619fe6608d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('super_market_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['super_market_id'], ['supermarkets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
